sudo: required

language: generic

dist: bionic

addons:
  apt:
    update: true
    packages: 
      - jq 
      - make

services:
  - validate

stages:
  - build

before_script:
  - sudo apt-cache policy make

jobs:
  include:
    - stage: validate
      script: make validate
